### ISSUE TITLE
Multiple Icons not working

### ISSUE THREAD

**Issue by jcddcjjcd** [HavenDV/H.NotifyIcon#33]
### Describe the bug

On Windows 11 and net v6 I am unable to produce more than one icon in both console and Wpf apps.
On setting an Icon for the second TaskBarIcon the first disappears.

This can be reproduced on the console version of the downloadable expample project.

### Expected behavior

Mulitple icons as in v1.xx of the library.

### NuGet package version

2.0.59
With the Console app below start it up and the type "create-second"
[TestTrayIcon.zip](https://github.com/HavenDV/H.NotifyIcon/files/9297312/TestTrayIcon.zip)

### Platform

WPF, Console

### Windows Version

Windows 11

**Comment by HavenDV** [comment]
I opted out of automatically generating a new Guid each time a TrayIcon was created, because it caused problems with saving trayicon settings in the system. Hashing is now used to ensure that the same Guid is generated based on the location of the calling library and some prefix, which is empty by default. To fix your problem, just use the TrayIcon("Second") constructor which allows you to set this prefix

**Comment by jcddcjjcd** [comment]
Very satisfactory. Thanks so much for your great work.
Regards, John.

**Comment by jcddcjjcd** [comment]
Upon further testing I noticed that while your solution works for H.NotifyIcon.core it has not been implemented for H.NotifyIcon.Wpf which uses tbrIcon = new TaskbarIcon() and does not take a parameter.
Is this correct?
Regards, John.

**Comment by HavenDV** [comment]
There are also two methods that allow you to do this:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/3002068/184059578-62473d03-af1f-4387-bf1d-b0ce867f818d.png">
They are bound to Id and CustomName DependencyProperty:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/3002068/184059753-862de7c9-e16d-408b-8a33-392b142bf173.png">

**Comment by jcddcjjcd** [comment]
Thank very much.
Regards, John.
