### ISSUE TITLE
GeneratedIconText Scale of Text

### ISSUE THREAD

**Issue by SinanAkkoyun** [HavenDV/H.NotifyIcon#39]
## What would you like to be added:
I would like to have the generated icon display the full text that it gets supplied and not only one to two chars.

## Why is this needed:
I want to display wattage numbers (very similar to HWInfos Tray Texts)

## For which Platform:

- [ ] All
- [ ] WPF
- [x] WinUI
- [ ] Uno
- [ ] Core

## Anything else we need to know?

Thanks for the awesome package :)

**Comment by SinanAkkoyun** [comment]
I am so sorry, I don't know how I could have not seen that but there is a FontSize property.
I am sorry for opening another issue...

**Comment by SinanAkkoyun** [comment]
Although I have one question, why can't it render "%" ?

**Comment by SinanAkkoyun** [comment]
I will repurpose this for another question:
<img width="52" alt="image" src="https://user-images.githubusercontent.com/43215895/190541910-f48892e0-bf2a-428c-ab49-4b09c8e8ada0.png">
The left is by using your code and the right is the app battery percentage icon.

I gave it 95 with the font size 30 but it will only spit out the one char. The battery icon app can show bigger numbers and two chars

How could I accomplish displaying two bigger chars?
Thanks very much

```xaml
<tb:GeneratedIcon
                Text="95"
                FontFamily="Arial"
                FontSize="50"
                Foreground="#80FFFF"
                BackgroundType="RoundedRectangle"
                />
        </tb:TaskbarIcon.GeneratedIcon>
```

**Comment by HavenDV** [comment]
Here you need to select the font family. Maybe I also didn't implement some setting that controls character spacing. You can also increase the size of the canvas using the Size property (default 128) to achieve the maximum size.

**Comment by HavenDV** [comment]
Related code:
https://github.com/HavenDV/H.NotifyIcon/blob/master/src/libs/H.NotifyIcon/IconGenerator.cs
https://github.com/HavenDV/H.NotifyIcon/blob/master/src/libs/H.NotifyIcon.Shared/GeneratedIcon.cs

I suspect the problem is that I'm using System.Drawing to generate text, which doesn't support specifying spacing between characters. Here is an open question on this topic on SO:
https://stackoverflow.com/questions/2969143/c-sharp-drawstring-letter-spacing

I will try to implement the suggested solution from here by binding it to the `FontStretch` property

**Comment by HavenDV** [comment]
I was able to get the size up to 55 in the latest update. Please test it.
